apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-consumer-deployment
  labels:
    app: consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: spiridon26/flask-consumer
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask-consumer-service
  namespace: kafka
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
