apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-svc
  namespace: kafka
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper-service.kafka.svc.cluster.local:2181
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-svc.kafka.svc.cluster.local:9092
        image: bitnami/kafka:latest
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092





        #zookeeper-service.kafka.svc.cluster.local