apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-producer-deployment2
  labels:
    app: producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer-python2
        image: spiridon26/producer-python2
        ports:
        - containerPort: 80
