apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-producer-deployment3
  labels:
    app: producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer-python
        image: spiridon26/busdata3-v3
        ports:
        - containerPort: 80
